name: Java backend CI pipeline

on:
  push:
    paths:
      - 'java-backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jhivern/java-build:latest  # contains OpenJDK 17

    steps:
      # Step 1: Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # Step 2: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 3: Cache Maven dependencies
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('java-backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build & test
      - name: Maven Build
        working-directory: java-backend
        run: mvn clean install
