name: Java Backend CI Pipeline

on:
  push:
    paths:
      - 'java-backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jhivern/java-build:latest # Custom Docker image using EclipseTemurin23
      options: --user root

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create cache directory if it does not exist
      - name: Ensure Maven directory exists
        run: mkdir -p ~/.m2/repository

      # Step 3: Cache Maven dependencies
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('java-backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build & test
      - name: Maven Build
        working-directory: java-backend
        run: mvn -B clean verify
