name: Java backend CI pipeline

on:
  push:
    paths:
      - 'java-backend/**'
  # pull_request:
  #   paths:
  #     - 'java-backend/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jhivern/java-build:latest  # contains OpenJDK 17
    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('java-backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Build
        working-directory: java-backend
        run: mvn clean install

