name: Java Backend CI Pipeline

on:
  push:
    paths:
      - 'java-backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-jdk-23  # public image with Maven + JDK 23

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Cache Maven dependencies
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('java-backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 3: Build & test
      - name: Maven Build
        working-directory: java-backend
        run: mvn clean install
